services:
  inventory:
#    image: gcepedag/proyecto-final:latest
    build: .
    networks:
      - my-network
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    depends_on:
      - database-mysql
    restart: always
  database-mysql:
    platform: linux/amd64
    image: mysql:5.7.26
    restart: always
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$DB_USER --password=$$DB_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_USER=$DB_USER
      - MYSQL_DATABASE=$DB_NAME
#    volumes:
#      - ${VOLUME_PATH}:/var/lib/mysql
    networks:
      - my-network
networks:
  my-network:
